use_frameworks!

platform :ios, '8.0'

target 'FHAlertView_Example' do
  pod 'FHAlertView', :path => '../'

  target 'FHAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
